export const cities = [
    "Ankola, Uttara Kannada, Karnataka, India",
    "Bagalkot, Bagalkot, Karnataka, India",
    "Badami, Bagalkot, Karnataka, India",
    "Bilgi, Bagalkot, Karnataka, India",
    "Hungund, Bagalkot, Karnataka, India",
    "Jamkhandi, Bagalkot, Karnataka, India",
    "Mudhol, Bagalkot, Karnataka, India",
    "Bangalore, Bengaluru Urban, Karnataka, India",
    "Anekal, Bengaluru Urban, Karnataka, India",
    "Devanahalli, Bengaluru Rural, Karnataka, India",
    "Doddaballapura, Bengaluru Rural, Karnataka, India",
    "Hosakote, Bengaluru Rural, Karnataka, India",
    "Nelamangala, Bengaluru Rural, Karnataka, India",
    "Belgaum, Belagavi, Karnataka, India",
    "Athani, Belagavi, Karnataka, India",
    "Bailhongal, Belagavi, Karnataka, India",
    "Chikkodi, Belagavi, Karnataka, India",
    "Gokak, Belagavi, Karnataka, India",
    "Hukkeri, Belagavi, Karnataka, India",
    "Khanapur, Belagavi, Karnataka, India",
    "Ramdurg, Belagavi, Karnataka, India",
    "Raybag, Belagavi, Karnataka, India",
    "Saundatti, Belagavi, Karnataka, India",
    "Bellary, Ballari, Karnataka, India",
    "Sandur, Ballari, Karnataka, India",
    "Siruguppa, Ballari, Karnataka, India",
    "Kampli, Ballari, Karnataka, India",
    "Bidar, Bidar, Karnataka, India",
    "Basavakalyan, Bidar, Karnataka, India",
    "Bhalki, Bidar, Karnataka, India",
    "Homnabad, Bidar, Karnataka, India",
    "Aurad, Bidar, Karnataka, India",
    "Vijayapura, Vijayapura, Karnataka, India",
    "Basavana Bagevadi, Vijayapura, Karnataka, India",
    "Indi, Vijayapura, Karnataka, India",
    "Muddebihal, Vijayapura, Karnataka, India",
    "Sindgi, Vijayapura, Karnataka, India",
    "Chamarajanagar, Chamarajanagar, Karnataka, India",
    "Gundlupet, Chamarajanagar, Karnataka, India",
    "Kollegal, Chamarajanagar, Karnataka, India",
    "Yelandur, Chamarajanagar, Karnataka, India",
    "Chikkaballapur, Chikkaballapur, Karnataka, India",
    "Bagepalli, Chikkaballapur, Karnataka, India",
    "Chintamani, Chikkaballapur, Karnataka, India",
    "Gauribidanur, Chikkaballapur, Karnataka, India",
    "Gudibanda, Chikkaballapur, Karnataka, India",
    "Sidlaghatta, Chikkaballapur, Karnataka, India",
    "Chikkamagaluru, Chikkamagaluru, Karnataka, India",
    "Kadur, Chikkamagaluru, Karnataka, India",
    "Koppa, Chikkamagaluru, Karnataka, India",
    "Mudigere, Chikkamagaluru, Karnataka, India",
    "Narasimharajapura, Chikkamagaluru, Karnataka, India",
    "Sringeri, Chikkamagaluru, Karnataka, India",
    "Tarikere, Chikkamagaluru, Karnataka, India",
    "Chitradurga, Chitradurga, Karnataka, India",
    "Challakere, Chitradurga, Karnataka, India",
    "Hiriyur, Chitradurga, Karnataka, India",
    "Holalkere, Chitradurga, Karnataka, India",
    "Hosadurga, Chitradurga, Karnataka, India",
    "Molakalmuru, Chitradurga, Karnataka, India",
    "Mangalore, Dakshina Kannada, Karnataka, India",
    "Bantwal, Dakshina Kannada, Karnataka, India",
    "Beltangady, Dakshina Kannada, Karnataka, India",
    "Puttur, Dakshina Kannada, Karnataka, India",
    "Sullia, Dakshina Kannada, Karnataka, India",
    "Davanagere, Davanagere, Karnataka, India",
    "Harihar, Davanagere, Karnataka, India",
    "Honnali, Davanagere, Karnataka, India",
    "Channagiri, Davanagere, Karnataka, India",
    "Jagalur, Davanagere, Karnataka, India",
    "Dharwad, Dharwad, Karnataka, India",
    "Hubli, Dharwad, Karnataka, India",
    "Kalghatgi, Dharwad, Karnataka, India",
    "Kundgol, Dharwad, Karnataka, India",
    "Navalund, Dharwad, Karnataka, India",
    "Gadag, Gadag, Karnataka, India",
    "Mundargi, Gadag, Karnataka, India",
    "Nargund, Gadag, Karnataka, India",
    "Ron, Gadag, Karnataka, India",
    "Shirahatti, Gadag, Karnataka, India",
    "Kalaburagi, Kalaburagi, Karnataka, India",
    "Afzalpur, Kalaburagi, Karnataka, India",
    "Aland, Kalaburagi, Karnataka, India",
    "Chincholi, Kalaburagi, Karnataka, India",
    "Chittapur, Kalaburagi, Karnataka, India",
    "Jewargi, Kalaburagi, Karnataka, India",
    "Sedam, Kalaburagi, Karnataka, India",
    "Hassan, Hassan, Karnataka, India",
    "Alur, Hassan, Karnataka, India",
    "Arkalgud, Hassan, Karnataka, India",
    "Arsikere, Hassan, Karnataka, India",
    "Belur, Hassan, Karnataka, India",
    "Channarayapatna, Hassan, Karnataka, India",
    "Holenarasipura, Hassan, Karnataka, India",
    "Sakleshpur, Hassan, Karnataka, India",
    "Haveri, Haveri, Karnataka, India",
    "Byadagi, Haveri, Karnataka, India",
    "Hanagal, Haveri, Karnataka, India",
    "Hirekerur, Haveri, Karnataka, India",
    "Ranibennur, Haveri, Karnataka, India",
    "Savanur, Haveri, Karnataka, India",
    "Shiggaon, Haveri, Karnataka, India",
    "Madikeri, Kodagu, Karnataka, India",
    "Somwarpet, Kodagu, Karnataka, India",
    "Virajpet, Kodagu, Karnataka, India",
    "Kolar, Kolar, Karnataka, India",
    "Bangarapet, Kolar, Karnataka, India",
    "Malur, Kolar, Karnataka, India",
    "Mulbagal, Kolar, Karnataka, India",
    "Srinivaspur, Kolar, Karnataka, India",
    "Koppal, Koppal, Karnataka, India",
    "Gangavathi, Koppal, Karnataka, India",
    "Kushtagi, Koppal, Karnataka, India",
    "Yelburga, Koppal, Karnataka, India",
    "Mandya, Mandya, Karnataka, India",
    "Maddur, Mandya, Karnataka, India",
    "Malavalli, Mandya, Karnataka, India",
    "Nagamangala, Mandya, Karnataka, India",
    "Pandavapura, Mandya, Karnataka, India",
    "Krishnarajpet, Mandya, Karnataka, India",
    "Srirangapatna, Mandya, Karnataka, India",
    "Mysuru, Mysuru, Karnataka, India",
    "Hunsur, Mysuru, Karnataka, India",
    "K.R. Nagar, Mysuru, Karnataka, India",
    "Nanjangud, Mysuru, Karnataka, India",
    "Periyapatna, Mysuru, Karnataka, India",
    "T. Narasipura, Mysuru, Karnataka, India",
    "Saragur, Mysuru, Karnataka, India",
    "Raichur, Raichur, Karnataka, India",
    "Deodurga, Raichur, Karnataka, India",
    "Lingsugur, Raichur, Karnataka, India",
    "Manvi, Raichur, Karnataka, India",
    "Sindhanur, Raichur, Karnataka, India",
    "Ramanagara, Ramanagara, Karnataka, India",
    "Channapatna, Ramanagara, Karnataka, India",
    "Kanakapura, Ramanagara, Karnataka, India",
    "Magadi, Ramanagara, Karnataka, India",
    "Shivamogga, Shivamogga, Karnataka, India",
    "Bhadravathi, Shivamogga, Karnataka, India",
    "Hosanagara, Shivamogga, Karnataka, India",
    "Sagar, Shivamogga, Karnataka, India",
    "Shikaripura, Shivamogga, Karnataka, India",
    "Soraba, Shivamogga, Karnataka, India",
    "Thirthahalli, Shivamogga, Karnataka, India",
    "Tumakuru, Tumakuru, Karnataka, India",
    "Chiknayakanhalli, Tumakuru, Karnataka, India",
    "Gubbi, Tumakuru, Karnataka, India",
    "Koratagere, Tumakuru, Karnataka, India",
    "Kunigal, Tumakuru, Karnataka, India",
    "Madhugiri, Tumakuru, Karnataka, India",
    "Pavagada, Tumakuru, Karnataka, India",
    "Sira, Tumakuru, Karnataka, India",
    "Tiptur, Tumakuru, Karnataka, India",
    "Turuvekere, Tumakuru, Karnataka, India",
    "Udupi, Udupi, Karnataka, India",
    "Karkala, Udupi, Karnataka, India",
    "Kundapura, Udupi, Karnataka, India",
    "Byndoor, Udupi, Karnataka, India",
    "Brahmavar, Udupi, Karnataka, India",
    "Kaup, Udupi, Karnataka, India",
    "Hebri, Udupi, Karnataka, India",
    "Karwar, Uttara Kannada, Karnataka, India",
    "Ankola, Uttara Kannada, Karnataka, India",
    "Bhatkal, Uttara Kannada, Karnataka, India",
    "Haliyal, Uttara Kannada, Karnataka, India",
    "Honnavar, Uttara Kannada, Karnataka, India",
    "Joida, Uttara Kannada, Karnataka, India",
    "Kumta, Uttara Kannada, Karnataka, India",
    "Mundgod, Uttara Kannada, Karnataka, India",
    "Siddapur, Uttara Kannada, Karnataka, India",
    "Sirsi, Uttara Kannada, Karnataka, India",
    "Yellapur, Uttara Kannada, Karnataka, India",
    "Yadgir, Yadgir, Karnataka, India",
    "Shahapur, Yadgir, Karnataka, India",
    "Shorapur, Yadgir, Karnataka, India",
    "Other/Outside Karnataka",
];

export const colleges = [
    "Indian Institute of Science (IISc), Bangalore",
    "National Institute of Technology Karnataka (NITK), Surathkal",
    "International Institute of Information Technology (IIIT), Bangalore",
    "Visvesvaraya Technological University (VTU), Belagavi",
    "Manipal Academy of Higher Education (MAHE), Manipal",
    "RV College of Engineering (RVCE), Bangalore",
    "BMS College of Engineering (BMSCE), Bangalore",
    "M.S. Ramaiah Institute of Technology (MSRIT), Bangalore",
    "PES University, Bangalore",
    "Bangalore University, Bangalore",
    "Mysore University, Mysuru",
    "Karnatak University, Dharwad",
    "Gulbarga University, Kalaburagi",
    "Mangalore University, Mangaluru",
    "Kuvempu University, Shivamogga",
    "University of Agricultural Sciences (UAS), Bangalore",
    "University of Agricultural Sciences (UAS), Dharwad",
    "Karnataka State Open University (KSOU), Mysuru",
    "Bangalore Institute of Technology (BIT), Bangalore",
    "UVCE, Bangalore",
    "Vidyavardhaka College of Engineering, Mysuru",
    "National Institute of Engineering (NIE), Mysuru",
    "JSS Science and Technology University (SJCE), Mysuru",
    "Malnad College of Engineering (MCE), Hassan",
    "BVB College of Engineering and Technology (KLE Tech), Hubballi",
    "SDM College of Engineering and Technology, Dharwad",
    "KLS Gogte Institute of Technology (GIT), Belagavi",
    "Basaveshwar Engineering College (BEC), Bagalkot",
    "PDA College of Engineering, Kalaburagi",
    "Ballari Institute of Technology and Management, Ballari",
    "NMAM Institute of Technology, Nitte",
    "Sahyadri College of Engineering and Management, Mangaluru",
    "St. Joseph Engineering College, Mangaluru",
    "Canara Engineering College, Mangaluru",
    "SIT, Tumkur",
    "Christ University, Bangalore",
    "Jain University, Bangalore",
    "Alliance University, Bangalore",
    "Reva University, Bangalore",
    "Dayananda Sagar College of Engineering, Bangalore",
    "Others",
];

export const languages = [
    "Kannada", "Konkani", "Tulu", "Kodava", "Marathi", "Hindi", "English", "Telugu", "Tamil", "Malayalam", "Gujarati", "Bengali", "Punjabi"
];
