export const cities = [
    "Ankola, Karnataka, India",
    "Ankolvadi, Gujarat, India",
    "Ankoli, Maharashtra, India",
    "Ankoli, Telangana, India",
    "Bangalore, Karnataka, India",
    "Mumbai, Maharashtra, India",
    "Delhi, Delhi, India",
    "Chennai, Tamil Nadu, India",
    "Hyderabad, Telangana, India",
    "Pune, Maharashtra, India",
    "Ahmedabad, Gujarat, India",
    "Kolkata, West Bengal, India",
    "Surat, Gujarat, India",
    "Jaipur, Rajasthan, India",
    "Lucknow, Uttar Pradesh, India",
    "Kanpur, Uttar Pradesh, India",
    "Nagpur, Maharashtra, India",
    "Indore, Madhya Pradesh, India",
    "Thane, Maharashtra, India",
    "Bhopal, Madhya Pradesh, India",
    "Visakhapatnam, Andhra Pradesh, India",
    "Pimpri-Chinchwad, Maharashtra, India",
    "Patna, Bihar, India",
    "Vadodara, Gujarat, India",
    "Ghaziabad, Uttar Pradesh, India",
    "Ludhiana, Punjab, India",
    "Agra, Uttar Pradesh, India",
    "Nashik, Maharashtra, India",
    "Faridabad, Haryana, India",
    "Meerut, Uttar Pradesh, India",
    "Rajkot, Gujarat, India",
    "Kalyan-Dombivli, Maharashtra, India",
    "Vasai-Virar, Maharashtra, India",
    "Varanasi, Uttar Pradesh, India",
    "Srinagar, Jammu and Kashmir, India",
    "Aurangabad, Maharashtra, India",
    "Dhanbad, Jharkhand, India",
    "Amritsar, Punjab, India",
    "Navi Mumbai, Maharashtra, India",
    "Allahabad, Uttar Pradesh, India",
    "Ranchi, Jharkhand, India",
    "Howrah, West Bengal, India",
    "Coimbatore, Tamil Nadu, India",
    "Jabalpur, Madhya Pradesh, India",
    "Gwalior, Madhya Pradesh, India",
    "Vijayawada, Andhra Pradesh, India",
    "Jodhpur, Rajasthan, India",
    "Madurai, Tamil Nadu, India",
    "Raipur, Chhattisgarh, India",
    "Kota, Rajasthan, India",
];

export const colleges = [
    "Indian Institute of Technology (IIT) Bombay",
    "Indian Institute of Technology (IIT) Delhi",
    "Indian Institute of Technology (IIT) Madras",
    "Indian Institute of Technology (IIT) Kanpur",
    "Indian Institute of Technology (IIT) Kharagpur",
    "Indian Institute of Technology (IIT) Roorkee",
    "Indian Institute of Technology (IIT) Guwahati",
    "Indian Institute of Science (IISc) Bangalore",
    "National Institute of Technology (NIT) Trichy",
    "National Institute of Technology (NIT) Surathkal",
    "National Institute of Technology (NIT) Warangal",
    "BITS Pilani",
    "Delhi Technological University (DTU)",
    "Anna University, Chennai",
    "Jadavpur University, Kolkata",
    "Banaras Hindu University (BHU), Varanasi",
    "University of Delhi (DU)",
    "Manipal Academy of Higher Education",
    "Vellore Institute of Technology (VIT)",
    "SRM Institute of Science and Technology",
    "Amity University",
    "Lovely Professional University (LPU)",
    "Symbiosis International University, Pune",
    "Christ University, Bangalore",
    "St. Stephen's College, Delhi",
    "LSR College for Women, Delhi",
    "Miranda House, Delhi",
    "Hansraj College, Delhi",
    "Hindu College, Delhi",
    "St. Xavier's College, Mumbai",
    "St. Xavier's College, Kolkata",
    "Loyola College, Chennai",
    "Madras Christian College (MCC)",
    "Fergusson College, Pune",
    "Mount Carmel College, Bangalore",
];
